# Generated by Django 3.2 on 2026-01-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20260120_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
